name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2  
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
          weight: 900
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter-Thin.ttf
          weight: 100


      