name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  expandable_text: ^2.3.0
  marquee: ^2.2.3
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  cupertino_icons: ^1.0.2  
  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  flutter_native_splash: ^2.4.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  google_sign_in: ^6.2.1
  email_otp: ^3.0.1
  custom_clippers: ^2.0.0
  uuid: ^4.4.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  curved_labeled_navigation_bar: ^2.0.2
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.13.1
  firebase_storage: ^12.1.0
  firebase_messaging: ^15.0.2
  provider: ^6.1.2
  diacritic: ^0.1.5
  camera: ^0.11.0+1
  get: ^4.6.6
  video_compress: ^3.1.2
  chewie: ^1.8.1
  video_player: ^2.9.1
  shared_preferences: ^2.0.13
  path_provider: ^2.1.3
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  flutter_notification_channel: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  snippet_coder_utils: ^1.0.15

flutter_native_splash:
  color: "#000141"
  image: assets/images/ReelReplay2.png
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_launcher.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/videos/
    - assets/videos/loading.json

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
          weight: 900
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter-Thin.ttf
          weight: 100


      