name: mobile_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  expandable_text: ^2.3.0
  marquee: ^2.2.3
  google_fonts: ^6.2.1
  video_player: ^2.8.6
  lottie: ^1.1.0
  cupertino_icons: ^1.0.2  
  flutter_svg: ^2.0.10+1
  http: ^1.0.0
  flutter_native_splash: ^2.4.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.2.1
  email_otp: ^2.1.2
  custom_clippers: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  snippet_coder_utils: ^1.0.15

flutter_native_splash:
  color: "#000141"
  image: assets/images/ReelReplay2.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/videos/
    - assets/videos/loading.json

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Black.ttf
          weight: 900
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter-Thin.ttf
          weight: 100


      